apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "ubuntu-ch-jammy"
spec:
  storage:
    resources:
      requests:
        storage: 10Gi
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
  source:
    http:
      url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
