apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blank-block-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo-immeidate 
