// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.2
// source: pkg/daemon/proto/daemon.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmAction int32

const (
	VmAction_Unknown VmAction = 0
	VmAction_Paused  VmAction = 1
	VmAction_Resumed VmAction = 2
)

// Enum value maps for VmAction.
var (
	VmAction_name = map[int32]string{
		0: "Unknown",
		1: "Paused",
		2: "Resumed",
	}
	VmAction_value = map[string]int32{
		"Unknown": 0,
		"Paused":  1,
		"Resumed": 2,
	}
)

func (x VmAction) Enum() *VmAction {
	p := new(VmAction)
	*p = x
	return p
}

func (x VmAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VmAction) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_daemon_proto_daemon_proto_enumTypes[0].Descriptor()
}

func (VmAction) Type() protoreflect.EnumType {
	return &file_pkg_daemon_proto_daemon_proto_enumTypes[0]
}

func (x VmAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VmAction.Descriptor instead.
func (VmAction) EnumDescriptor() ([]byte, []int) {
	return file_pkg_daemon_proto_daemon_proto_rawDescGZIP(), []int{0}
}

type GetVmstatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vmname    string `protobuf:"bytes,1,opt,name=vmname,proto3" json:"vmname,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *GetVmstatusRequest) Reset() {
	*x = GetVmstatusRequest{}
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmstatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmstatusRequest) ProtoMessage() {}

func (x *GetVmstatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmstatusRequest.ProtoReflect.Descriptor instead.
func (*GetVmstatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_daemon_proto_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *GetVmstatusRequest) GetVmname() string {
	if x != nil {
		return x.Vmname
	}
	return ""
}

func (x *GetVmstatusRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type VmStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Vmpodname string `protobuf:"bytes,3,opt,name=vmpodname,proto3" json:"vmpodname,omitempty"`
	Vmpoduid  string `protobuf:"bytes,4,opt,name=vmpoduid,proto3" json:"vmpoduid,omitempty"`
}

func (x *VmStatus) Reset() {
	*x = VmStatus{}
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmStatus) ProtoMessage() {}

func (x *VmStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmStatus.ProtoReflect.Descriptor instead.
func (*VmStatus) Descriptor() ([]byte, []int) {
	return file_pkg_daemon_proto_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *VmStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VmStatus) GetVmpodname() string {
	if x != nil {
		return x.Vmpodname
	}
	return ""
}

func (x *VmStatus) GetVmpoduid() string {
	if x != nil {
		return x.Vmpoduid
	}
	return ""
}

type GetVmStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *VmStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetVmStatusResponse) Reset() {
	*x = GetVmStatusResponse{}
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmStatusResponse) ProtoMessage() {}

func (x *GetVmStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmStatusResponse.ProtoReflect.Descriptor instead.
func (*GetVmStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_daemon_proto_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *GetVmStatusResponse) GetStatus() *VmStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type PauseVMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *PauseVMRequest) Reset() {
	*x = PauseVMRequest{}
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseVMRequest) ProtoMessage() {}

func (x *PauseVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseVMRequest.ProtoReflect.Descriptor instead.
func (*PauseVMRequest) Descriptor() ([]byte, []int) {
	return file_pkg_daemon_proto_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *PauseVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PauseVMRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ResumeVMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *ResumeVMRequest) Reset() {
	*x = ResumeVMRequest{}
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeVMRequest) ProtoMessage() {}

func (x *ResumeVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeVMRequest.ProtoReflect.Descriptor instead.
func (*ResumeVMRequest) Descriptor() ([]byte, []int) {
	return file_pkg_daemon_proto_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *ResumeVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResumeVMRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type RebootVMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *RebootVMRequest) Reset() {
	*x = RebootVMRequest{}
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebootVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebootVMRequest) ProtoMessage() {}

func (x *RebootVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebootVMRequest.ProtoReflect.Descriptor instead.
func (*RebootVMRequest) Descriptor() ([]byte, []int) {
	return file_pkg_daemon_proto_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *RebootVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RebootVMRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type CreateVMSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace   string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Upload      bool   `protobuf:"varint,5,opt,name=upload,proto3" json:"upload,omitempty"`
	S3Bucket    string `protobuf:"bytes,6,opt,name=s3bucket,proto3" json:"s3bucket,omitempty"`
	Gcsbucket   string `protobuf:"bytes,7,opt,name=gcsbucket,proto3" json:"gcsbucket,omitempty"`
}

func (x *CreateVMSnapshot) Reset() {
	*x = CreateVMSnapshot{}
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMSnapshot) ProtoMessage() {}

func (x *CreateVMSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMSnapshot.ProtoReflect.Descriptor instead.
func (*CreateVMSnapshot) Descriptor() ([]byte, []int) {
	return file_pkg_daemon_proto_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *CreateVMSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateVMSnapshot) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateVMSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVMSnapshot) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateVMSnapshot) GetUpload() bool {
	if x != nil {
		return x.Upload
	}
	return false
}

func (x *CreateVMSnapshot) GetS3Bucket() string {
	if x != nil {
		return x.S3Bucket
	}
	return ""
}

func (x *CreateVMSnapshot) GetGcsbucket() string {
	if x != nil {
		return x.Gcsbucket
	}
	return ""
}

type RestoreVMSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace   string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *RestoreVMSnapshot) Reset() {
	*x = RestoreVMSnapshot{}
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreVMSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreVMSnapshot) ProtoMessage() {}

func (x *RestoreVMSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_daemon_proto_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreVMSnapshot.ProtoReflect.Descriptor instead.
func (*RestoreVMSnapshot) Descriptor() ([]byte, []int) {
	return file_pkg_daemon_proto_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *RestoreVMSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestoreVMSnapshot) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RestoreVMSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestoreVMSnapshot) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_pkg_daemon_proto_daemon_proto protoreflect.FileDescriptor

var file_pkg_daemon_proto_daemon_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x76, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x6d,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x6d, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76,
	0x6d, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x22, 0x5c, 0x0a, 0x08, 0x56, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x6d, 0x70, 0x6f, 0x64,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x6d, 0x70, 0x6f,
	0x64, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x6d, 0x70, 0x6f, 0x64, 0x75, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x6d, 0x70, 0x6f, 0x64, 0x75, 0x69,
	0x64, 0x22, 0x42, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x56, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x6d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x42, 0x0a, 0x0e, 0x50, 0x61, 0x75, 0x73, 0x65, 0x56, 0x4d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x43, 0x0a, 0x0f, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x43,
	0x0a, 0x0f, 0x52, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x22, 0xc8, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x4d,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x33, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x33, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x67, 0x63, 0x73, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x63, 0x73, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x77,
	0x0a, 0x11, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x4d, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2a, 0x30, 0x0a, 0x08, 0x56, 0x6d, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x50, 0x61, 0x75, 0x73, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x10, 0x02, 0x32, 0xa7, 0x03, 0x0a, 0x09, 0x56, 0x6d,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x4d,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x2e, 0x76, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x50, 0x61, 0x75, 0x73, 0x65, 0x56, 0x4d,
	0x12, 0x19, 0x2e, 0x76, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x75,
	0x73, 0x65, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x3e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x56, 0x4d, 0x12,
	0x1a, 0x2e, 0x76, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x3e, 0x0a, 0x08, 0x52, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x56, 0x4d, 0x12,
	0x1a, 0x2e, 0x76, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x62, 0x6f,
	0x6f, 0x74, 0x56, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x45, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x1b, 0x2e, 0x76, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x4d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x47, 0x0a, 0x0f, 0x52, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x1c, 0x2e,
	0x76, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x56, 0x4d, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x61, 0x6c, 0x61, 0x6a, 0x61, 0x6c, 0x61, 0x34, 0x6e, 0x61, 0x72, 0x65, 0x73,
	0x68, 0x2f, 0x76, 0x69, 0x72, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_daemon_proto_daemon_proto_rawDescOnce sync.Once
	file_pkg_daemon_proto_daemon_proto_rawDescData = file_pkg_daemon_proto_daemon_proto_rawDesc
)

func file_pkg_daemon_proto_daemon_proto_rawDescGZIP() []byte {
	file_pkg_daemon_proto_daemon_proto_rawDescOnce.Do(func() {
		file_pkg_daemon_proto_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_daemon_proto_daemon_proto_rawDescData)
	})
	return file_pkg_daemon_proto_daemon_proto_rawDescData
}

var file_pkg_daemon_proto_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_daemon_proto_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_daemon_proto_daemon_proto_goTypes = []any{
	(VmAction)(0),               // 0: vmservice.VmAction
	(*GetVmstatusRequest)(nil),  // 1: vmservice.GetVmstatusRequest
	(*VmStatus)(nil),            // 2: vmservice.VmStatus
	(*GetVmStatusResponse)(nil), // 3: vmservice.GetVmStatusResponse
	(*PauseVMRequest)(nil),      // 4: vmservice.PauseVMRequest
	(*ResumeVMRequest)(nil),     // 5: vmservice.ResumeVMRequest
	(*RebootVMRequest)(nil),     // 6: vmservice.RebootVMRequest
	(*CreateVMSnapshot)(nil),    // 7: vmservice.CreateVMSnapshot
	(*RestoreVMSnapshot)(nil),   // 8: vmservice.RestoreVMSnapshot
	(*emptypb.Empty)(nil),       // 9: google.protobuf.Empty
}
var file_pkg_daemon_proto_daemon_proto_depIdxs = []int32{
	2, // 0: vmservice.GetVmStatusResponse.status:type_name -> vmservice.VmStatus
	1, // 1: vmservice.VmService.GetVMStatus:input_type -> vmservice.GetVmstatusRequest
	4, // 2: vmservice.VmService.PauseVM:input_type -> vmservice.PauseVMRequest
	5, // 3: vmservice.VmService.ResumeVM:input_type -> vmservice.ResumeVMRequest
	6, // 4: vmservice.VmService.RebootVM:input_type -> vmservice.RebootVMRequest
	7, // 5: vmservice.VmService.CreateSnapshot:input_type -> vmservice.CreateVMSnapshot
	8, // 6: vmservice.VmService.RestoreSnapshot:input_type -> vmservice.RestoreVMSnapshot
	3, // 7: vmservice.VmService.GetVMStatus:output_type -> vmservice.GetVmStatusResponse
	9, // 8: vmservice.VmService.PauseVM:output_type -> google.protobuf.Empty
	9, // 9: vmservice.VmService.ResumeVM:output_type -> google.protobuf.Empty
	9, // 10: vmservice.VmService.RebootVM:output_type -> google.protobuf.Empty
	9, // 11: vmservice.VmService.CreateSnapshot:output_type -> google.protobuf.Empty
	9, // 12: vmservice.VmService.RestoreSnapshot:output_type -> google.protobuf.Empty
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_daemon_proto_daemon_proto_init() }
func file_pkg_daemon_proto_daemon_proto_init() {
	if File_pkg_daemon_proto_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_daemon_proto_daemon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_daemon_proto_daemon_proto_goTypes,
		DependencyIndexes: file_pkg_daemon_proto_daemon_proto_depIdxs,
		EnumInfos:         file_pkg_daemon_proto_daemon_proto_enumTypes,
		MessageInfos:      file_pkg_daemon_proto_daemon_proto_msgTypes,
	}.Build()
	File_pkg_daemon_proto_daemon_proto = out.File
	file_pkg_daemon_proto_daemon_proto_rawDesc = nil
	file_pkg_daemon_proto_daemon_proto_goTypes = nil
	file_pkg_daemon_proto_daemon_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VmServiceClient is the client API for VmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VmServiceClient interface {
	GetVMStatus(ctx context.Context, in *GetVmstatusRequest, opts ...grpc.CallOption) (*GetVmStatusResponse, error)
	PauseVM(ctx context.Context, in *PauseVMRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResumeVM(ctx context.Context, in *ResumeVMRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RebootVM(ctx context.Context, in *RebootVMRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateSnapshot(ctx context.Context, in *CreateVMSnapshot, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RestoreSnapshot(ctx context.Context, in *RestoreVMSnapshot, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type vmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVmServiceClient(cc grpc.ClientConnInterface) VmServiceClient {
	return &vmServiceClient{cc}
}

func (c *vmServiceClient) GetVMStatus(ctx context.Context, in *GetVmstatusRequest, opts ...grpc.CallOption) (*GetVmStatusResponse, error) {
	out := new(GetVmStatusResponse)
	err := c.cc.Invoke(ctx, "/vmservice.VmService/GetVMStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) PauseVM(ctx context.Context, in *PauseVMRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/vmservice.VmService/PauseVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) ResumeVM(ctx context.Context, in *ResumeVMRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/vmservice.VmService/ResumeVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) RebootVM(ctx context.Context, in *RebootVMRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/vmservice.VmService/RebootVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) CreateSnapshot(ctx context.Context, in *CreateVMSnapshot, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/vmservice.VmService/CreateSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vmServiceClient) RestoreSnapshot(ctx context.Context, in *RestoreVMSnapshot, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/vmservice.VmService/RestoreSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VmServiceServer is the server API for VmService service.
type VmServiceServer interface {
	GetVMStatus(context.Context, *GetVmstatusRequest) (*GetVmStatusResponse, error)
	PauseVM(context.Context, *PauseVMRequest) (*emptypb.Empty, error)
	ResumeVM(context.Context, *ResumeVMRequest) (*emptypb.Empty, error)
	RebootVM(context.Context, *RebootVMRequest) (*emptypb.Empty, error)
	CreateSnapshot(context.Context, *CreateVMSnapshot) (*emptypb.Empty, error)
	RestoreSnapshot(context.Context, *RestoreVMSnapshot) (*emptypb.Empty, error)
}

// UnimplementedVmServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVmServiceServer struct {
}

func (*UnimplementedVmServiceServer) GetVMStatus(context.Context, *GetVmstatusRequest) (*GetVmStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVMStatus not implemented")
}
func (*UnimplementedVmServiceServer) PauseVM(context.Context, *PauseVMRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseVM not implemented")
}
func (*UnimplementedVmServiceServer) ResumeVM(context.Context, *ResumeVMRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeVM not implemented")
}
func (*UnimplementedVmServiceServer) RebootVM(context.Context, *RebootVMRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebootVM not implemented")
}
func (*UnimplementedVmServiceServer) CreateSnapshot(context.Context, *CreateVMSnapshot) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (*UnimplementedVmServiceServer) RestoreSnapshot(context.Context, *RestoreVMSnapshot) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreSnapshot not implemented")
}

func RegisterVmServiceServer(s *grpc.Server, srv VmServiceServer) {
	s.RegisterService(&_VmService_serviceDesc, srv)
}

func _VmService_GetVMStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmstatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).GetVMStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vmservice.VmService/GetVMStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).GetVMStatus(ctx, req.(*GetVmstatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_PauseVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).PauseVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vmservice.VmService/PauseVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).PauseVM(ctx, req.(*PauseVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_ResumeVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).ResumeVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vmservice.VmService/ResumeVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).ResumeVM(ctx, req.(*ResumeVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_RebootVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).RebootVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vmservice.VmService/RebootVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).RebootVM(ctx, req.(*RebootVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMSnapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vmservice.VmService/CreateSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).CreateSnapshot(ctx, req.(*CreateVMSnapshot))
	}
	return interceptor(ctx, in, info, handler)
}

func _VmService_RestoreSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreVMSnapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VmServiceServer).RestoreSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vmservice.VmService/RestoreSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VmServiceServer).RestoreSnapshot(ctx, req.(*RestoreVMSnapshot))
	}
	return interceptor(ctx, in, info, handler)
}

var _VmService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vmservice.VmService",
	HandlerType: (*VmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVMStatus",
			Handler:    _VmService_GetVMStatus_Handler,
		},
		{
			MethodName: "PauseVM",
			Handler:    _VmService_PauseVM_Handler,
		},
		{
			MethodName: "ResumeVM",
			Handler:    _VmService_ResumeVM_Handler,
		},
		{
			MethodName: "RebootVM",
			Handler:    _VmService_RebootVM_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _VmService_CreateSnapshot_Handler,
		},
		{
			MethodName: "RestoreSnapshot",
			Handler:    _VmService_RestoreSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/daemon/proto/daemon.proto",
}
